const octave2 = [
  "C4",
  "Db4",
  "D4",
  "Eb4",
  "E4",
  "F4",
  "Gb4",
  "G4",
  "Ab4",
  "A4",
  "Bb4",
  "B4",
];
const octave3 = [
  "C5",
  "Db5",
  "D5",
  "Eb5",
  "E5",
  "F5",
  "Gb5",
  "G5",
  "Ab5",
  "A5",
  "Bb5",
  "B5",
];
const octave4 = [
  "C6",
  "Db6",
  "D6",
  "Eb6",
  "E6",
  "F6",
  "Gb6",
  "G6",
  "Ab6",
  "A6",
  "Bb6",
  "B6",
];
const octave5 = [
  "C7",
  "Db7",
  "D7",
  "Eb7",
  "E7",
  "F7",
  "Gb7",
  "G7",
  "Ab7",
  "A7",
  "Bb7",
  "B7",
];
const octave6 = ["C8"];

const key = [...octave2, ...octave3, ...octave4, ...octave5, ...octave6];
const InstrumentList = ["angklung", "bonang", "gambang", "saron"];
const note_to_key = [
  { from: "C5", to: "Q" },
  { from: "Db5", to: "2" },
  { from: "D5", to: "W" },
  { from: "Eb5", to: "3" },
  { from: "E5", to: "E" },
  { from: "F5", to: "R" },
  { from: "Gb5", to: "5" },
  { from: "G5", to: "T" },
  { from: "Ab5", to: "6" },
  { from: "A5", to: "Y" },
  { from: "Bb5", to: "7" },
  { from: "B5", to: "U" },
  { from: "C6", to: "Z" },
  { from: "Db6", to: "S" },
  { from: "D6", to: "X" },
  { from: "Eb6", to: "D" },
  { from: "E6", to: "C" },
  { from: "F6", to: "V" },
  { from: "Gb6", to: "G" },
  { from: "G6", to: "B" },
  { from: "Ab6", to: "H" },
  { from: "A6", to: "N" },
  { from: "Bb6", to: "J" },
  { from: "B6", to: "M" },
];
const key_to_note = {
  q: "C5",
  2: "Db5",
  w: "D5",
  3: "Eb5",
  e: "E5",
  r: "F5",
  5: "Gb5",
  t: "G5",
  6: "Ab5",
  y: "A5",
  7: "Bb5",
  u: "B5",
  z: "C6",
  s: "Db6",
  x: "D6",
  d: "Eb6",
  c: "E6",
  v: "F6",
  g: "Gb6",
  b: "G6",
  h: "Ab6",
  n: "A6",
  j: "Bb6",
  m: "B6",
};
const KeyWithInputIndexMin = 12;
const KeyWithInputIndexMax = 35;
export {
  key,
  InstrumentList,
  note_to_key,
  KeyWithInputIndexMin,
  KeyWithInputIndexMax,
  key_to_note,
};
