const octave2 = [
  "C3",
  "Db3",
  "D3",
  "Eb3",
  "E3",
  "b3",
  "Gb3",
  "G3",
  "Ab3",
  "A3",
  "Bb3",
  "B3",
];
const octave3 = [
  "C4",
  "Db4",
  "D4",
  "Eb4",
  "E4",
  "F4",
  "Gb4",
  "G4",
  "Ab4",
  "A4",
  "Bb4",
  "B4",
];
const octave4 = [
  "C5",
  "Db5",
  "D5",
  "Eb5",
  "E5",
  "F5",
  "Gb5",
  "G5",
  "Ab5",
  "A5",
  "Bb5",
  "B5",
];
const octave5 = [
  "C6",
  "Db6",
  "D6",
  "Eb6",
  "E6",
  "F6",
  "Gb6",
  "G6",
  "Ab6",
  "A6",
  "Bb6",
  "B6",
];
const octave6 = ["C7"];

const key = [...octave2, ...octave3, ...octave4, ...octave5, ...octave6];
const InstrumentList = ["angklung", "bonang", "gambang", "saron"];
const note_to_key = [
  { from: "C4", to: "Q" },
  { from: "Db4", to: "2" },
  { from: "D4", to: "W" },
  { from: "Eb4", to: "3" },
  { from: "E4", to: "E" },
  { from: "F4", to: "R" },
  { from: "Gb4", to: "5" },
  { from: "G4", to: "T" },
  { from: "Ab4", to: "6" },
  { from: "A4", to: "Y" },
  { from: "Bb4", to: "7" },
  { from: "B4", to: "U" },
  { from: "C5", to: "Z" },
  { from: "Db5", to: "S" },
  { from: "D5", to: "X" },
  { from: "Eb5", to: "D" },
  { from: "E5", to: "C" },
  { from: "F5", to: "V" },
  { from: "Gb5", to: "G" },
  { from: "G5", to: "B" },
  { from: "Ab5", to: "H" },
  { from: "A5", to: "N" },
  { from: "Bb5", to: "J" },
  { from: "B5", to: "M" },
];
const key_to_note = {
  q: "C5",
  2: "Db5",
  w: "D5",
  3: "Eb5",
  e: "E5",
  r: "F5",
  5: "Gb5",
  t: "G5",
  6: "Ab5",
  y: "A5",
  7: "Bb5",
  u: "B5",
  z: "C5",
  s: "Db5",
  x: "D5",
  d: "Eb5",
  c: "E5",
  v: "F5",
  g: "Gb5",
  b: "G5",
  h: "Ab5",
  n: "A5",
  j: "Bb5",
  m: "B5",
};
const KeyWithInputIndexMin = 12;
const KeyWithInputIndexMax = 35;
export {
  key,
  InstrumentList,
  note_to_key,
  KeyWithInputIndexMin,
  KeyWithInputIndexMax,
  key_to_note,
};
